import { Dosis } from "next/font/google";
import "@/public/css/bootstrap.min.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "@/public/css/globals.css";
import "@/public/css/header.css";
import "@/public/css/homepage.css";
import "@/public/css/blog.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { ToastContainer } from "react-toastify";

const dosis = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dosis.variable} antialiased`} >
        <ToastContainer />
        <Header />


        {children}



        <Footer />
      </body>
    </html>
  );
}
